import { Technique } from "@/lib/types";

export const TAXONOMY: Technique[] = [
  {
    id: "S1",
    name: "False Urgency",
    plainName: "Artificial time pressure",
    definition: "The manufactured imposition of time constraints to prevent deliberate evaluation. By compressing the perceived decision window, the technique bypasses System 2 analytical processing and forces a reactive, intuition-driven response.",
    theory: "Dual-process theory (Kahneman, 2011); Cialdini's Scarcity principle (2001); Elaboration Likelihood Model - urgency reduces motivation for central route processing (Petty & Cacioppo, 1986).",
    detection: [
      "Temporal markers: 'now', 'immediately', 'tonight', 'before it's too late'",
      "Countdown language: 'only X hours remaining', 'expires at midnight'",
      "Loss framing combined with time: 'lose your chance', 'miss out forever'",
      "Imperative verb constructions with temporal anchors",
    ],
    userLabel: "Artificial urgency - this content is applying time pressure that may be designed to prevent careful thinking.",
    level: 1,
  },
  {
    id: "S2",
    name: "Absolute Language",
    plainName: "False certainty",
    definition: "The presentation of contested, probabilistic, or unknown claims as established fact through categorical linguistic markers. Suppresses awareness of legitimate uncertainty and forecloses the possibility of alternative interpretations.",
    theory: "Epistemic cowardice literature (Frankfurt, 2005); Linguistic relativity - language structure shapes perception of certainty (Whorf, 1956); Misinformation and confidence calibration (Pennycook & Rand, 2019).",
    detection: [
      "Universal quantifiers: 'all', 'every', 'always', 'never', 'everyone knows'",
      "Epistemic markers of false certainty: 'the fact is', 'it is well established', 'undeniably'",
      "Absence of hedging language where hedging would be appropriate",
      "Present tense assertions about contested empirical claims",
    ],
    userLabel: "False certainty - this claim is presented as definite but may be contested or uncertain.",
    level: 1,
  },
  {
    id: "S3",
    name: "Loaded Language",
    plainName: "Emotionally charged framing",
    definition: "The deployment of words carrying strong emotional or ideological connotations beyond their denotative meaning to prime affective responses that bypass analytical evaluation. The linguistic choice does the persuasive work before the argument is even made.",
    theory: "Framing theory (Entman, 1993); Emotional contagion in language (Hatfield et al., 1994); Affect heuristic - emotional states bias risk and benefit judgements (Slovic et al., 2002).",
    detection: [
      "High-valence emotion words (LIWC emotional affect dictionaries)",
      "Politically coded terminology with contested neutrality",
      "Metaphors that activate specific emotional schema (war, invasion, disease)",
      "Euphemism and dysphemism patterns - softening or intensifying through word choice",
    ],
    userLabel: "Loaded language - the word choices here carry emotional charge that may be influencing your reaction before you've evaluated the argument.",
    level: 1,
  },
  {
    id: "S4",
    name: "Repetition as Emphasis",
    plainName: "Illusory truth through repetition",
    definition: "The strategic repetition of claims or phrases to create the psychological sensation of truth and familiarity independent of evidential support. Repeated exposure increases processing fluency, which is misattributed as a signal of truth.",
    theory: "Illusory truth effect (Hasher et al., 1977); Processing fluency and truth judgements (Reber & Schwarz, 1999); Propaganda technique - Big Lie repetition (Bernays, 1928).",
    detection: [
      "Identical or near-identical phrase repetition within a document",
      "Keyword density analysis - terms appearing at statistically elevated frequency",
      "Anaphoric repetition structures ('We will... We will... We will...')",
      "Slogan-like constructions repeated across multiple paragraphs",
    ],
    userLabel: "Strategic repetition - key phrases are being repeated in ways that may be designed to make them feel more true through familiarity rather than evidence.",
    level: 1,
  },
  {
    id: "S5",
    name: "Embedded Assumption",
    plainName: "Hidden premises in questions",
    definition: "The smuggling of contested claims into the structural presuppositions of questions or statements, making the acceptance of those claims a condition of engaging with the surface content at all. The reader agrees to the embedded assumption simply by reading.",
    theory: "Presupposition in linguistics (Levinson, 1983); Leading question research - memory distortion through embedded assumptions (Loftus & Palmer, 1974); Agenda-setting theory (McCombs & Shaw, 1972).",
    detection: [
      "Presuppositional question structures: 'Why does X always...' / 'When will they stop...'",
      "Definite descriptions implying contested existence: 'the failing NHS', 'the corrupt establishment'",
      "Causal constructions embedding unargued premises: 'since X is causing Y...'",
      "When-clauses that presuppose contested facts",
    ],
    userLabel: "Hidden assumption - this question or statement has an unargued claim built into its structure that you're being asked to accept without knowing it.",
    level: 1,
  },
  {
    id: "A1",
    name: "False Dichotomy",
    plainName: "Fake either/or choice",
    definition: "The presentation of a situation as offering only two mutually exclusive options when other possibilities exist, forcing the audience into a binary choice that advantages the position of the content producer. Artificially constrains the solution space.",
    theory: "Informal logic - fallacy of bifurcation (Walton, 1996); Cognitive closure need - binary thinking reduces uncertainty (Kruglanski, 1989); van der Linden & Roozenbeek manipulation technique taxonomy (2021).",
    detection: [
      "Binary connectives: 'either...or', 'if not X then Y', 'you're with us or against us'",
      "Exhaustiveness claims: 'there are only two options', 'the choice is simple'",
      "Absence of middle-ground or alternative framing in ostensibly exhaustive presentations",
      "Implicit false dichotomies in rhetorical questions",
    ],
    userLabel: "False choice - this presents only two options but other possibilities likely exist.",
    level: 2,
  },
  {
    id: "A2",
    name: "Scapegoating",
    plainName: "Single-cause blame",
    definition: "The attribution of complex, multi-causal social problems to a single identifiable group, individual, or phenomenon, displacing legitimate systemic critique onto a target that can be named, blamed, and excluded. Serves power by directing anger away from structural causes.",
    theory: "Scapegoat theory (Allport, 1954); Social identity theory - out-group derogation (Tajfel & Turner, 1979); Authoritarian personality research (Adorno et al., 1950); van der Linden manipulation technique taxonomy.",
    detection: [
      "Single-agent causation of complex phenomena: '[group] is responsible for [systemic problem]'",
      "Collective attribution language: 'they are destroying', 'the [group] agenda'",
      "Complexity reduction markers combined with blame attribution",
      "Historical pattern matching - problems attributed exclusively to named out-group",
    ],
    userLabel: "Scapegoating - a complex problem is being blamed entirely on one group, which likely oversimplifies the real causes.",
    level: 2,
  },
  {
    id: "A3",
    name: "Appeal to False Authority",
    plainName: "Misleading expert claims",
    definition: "The invocation of authority - real or fabricated - in domains where that authority does not apply, or the construction of false equivalence between marginal and mainstream expert opinion to manufacture the impression of legitimate scholarly dispute where none exists.",
    theory: "Cialdini's Authority principle (2001); Manufactured doubt strategy - tobacco and climate denial playbook (Oreskes & Conway, 2010); Epistemic authority and deference (Goldman, 2001).",
    detection: [
      "Authority invocation without domain specification: 'experts say', 'scientists confirm'",
      "False equivalence constructions: 'some scientists believe X, others believe Y' where consensus exists",
      "Credential inflation - non-specialist credentials applied to specialist claims",
      "Citation of retracted, predatory journal, or industry-funded research without disclosure",
    ],
    userLabel: "Misleading authority - an expert or authority is being cited in a way that may not reflect genuine expertise or mainstream evidence.",
    level: 2,
  },
  {
    id: "A4",
    name: "Whataboutism",
    plainName: "Deflection by comparison",
    definition: "The deflection of criticism by pointing to comparable or worse behaviour elsewhere, without engaging with the substance of the original criticism. Functions to normalise wrongdoing by relativising it and to exhaust the critic's attention through infinite regress of counter-examples.",
    theory: "Tu quoque fallacy (Walton, 1998); Soviet disinformation technique - documented deflection strategy (Galeotti, 2019); Moral disengagement - diffusion of responsibility through social comparison (Bandura, 1999).",
    detection: [
      "Counter-criticism pivots: 'but what about...', 'why aren't you talking about...'",
      "Comparative deflection without engaging original claim",
      "Asymmetric equivalence claims - constructing false moral equivalence",
      "Topic change to comparable actor following criticism of primary subject",
    ],
    userLabel: "Deflection - instead of addressing the point, this redirects to a different (often comparable) issue without engaging the original criticism.",
    level: 2,
  },
  {
    id: "A5",
    name: "Generalisation from Anecdote",
    plainName: "One story as universal proof",
    definition: "The use of individual cases, personal testimonies, or isolated examples as evidence for universal or statistical claims, exploiting the availability heuristic - the cognitive tendency to assess probability by the ease with which examples come to mind.",
    theory: "Availability heuristic (Tversky & Kahneman, 1973); Narrative transportation theory - stories bypass analytical processing (Green & Brock, 2000); Base rate neglect (Kahneman, 2011).",
    detection: [
      "Anecdote-to-universal inference markers: 'this proves that...', 'this shows us...'",
      "Personal testimony followed by statistical claim without bridge evidence",
      "Single case study generalised to population without qualification",
      "Vivid individual story used to counter aggregate statistical evidence",
    ],
    userLabel: "One story as proof - a single example or personal story is being used to support a much broader claim. Individual cases don't establish statistical patterns.",
    level: 2,
  },
  {
    id: "A6",
    name: "Gish Gallop",
    plainName: "Overwhelming with weak arguments",
    definition: "The rapid deployment of numerous low-quality arguments, objections, or claims in such volume that thorough refutation becomes practically impossible within the available time or space. Places the burden of exhaustive rebuttal on the target while the originator invests minimal effort per claim.",
    theory: "Asymmetric burden of proof exploitation (Hamblin, 1970); Information overload and decision quality (Eppler & Mengis, 2004); Debate tactic documented in creationism vs evolution discourse (Eugenie Scott, 1994).",
    detection: [
      "High claim density - statistically elevated number of distinct factual assertions per unit text",
      "Rapid topic shifts without sustained development of any single argument",
      "List structures containing multiple heterogeneous claims without evidential support",
      "Claims that individually require substantial context to evaluate",
    ],
    userLabel: "Argument flood - this content makes many rapid claims that would each require significant effort to check. Volume is being used as a substitute for quality.",
    level: 2,
  },
  {
    id: "P1",
    name: "In-group / Out-group Construction",
    plainName: "Us vs. them language",
    definition: "The deliberate linguistic construction of group boundaries that divide the social world into an valorised in-group (us) and a threatening or inferior out-group (them). Creates identity-protective cognition - resistance to information that threatens group membership - and can justify discrimination, exclusion, and dehumanisation through escalating linguistic steps.",
    theory: "Social identity theory (Tajfel & Turner, 1979); Terror management theory - in-group cohesion under threat (Greenberg et al., 1990); Dehumanisation language research (Haslam, 2006); Identity-protective cognition (Kahan et al., 2012).",
    detection: [
      "First-person plural vs. third-person plural opposition structures: 'we/our people' vs. 'they/them'",
      "In-group valorisation language combined with out-group threat language",
      "Membership boundary markers: who is included in 'real' [nationals/people/community]",
      "Dehumanising metaphors: animal, disease, infestation, flood imagery applied to out-group",
    ],
    userLabel: "Us vs. them construction - this content is drawing sharp boundaries between groups in ways that may be designed to trigger identity-protective reactions.",
    level: 3,
  },
  {
    id: "P2",
    name: "Naturalisation",
    plainName: "Making constructed things seem inevitable",
    definition: "The presentation of historically contingent, socially constructed arrangements - power hierarchies, economic systems, cultural norms - as natural, inevitable, or simply the way things are. Suppresses the visibility of the choices, interests, and power relations that produced them and forecloses the imagination of alternatives.",
    theory: "Critical discourse analysis - naturalisation as ideological function (Fairclough, 1992); Gramsci's hegemony - spontaneous consent to dominant order (1971); Bourdieu's doxa - taken-for-granted world (1977).",
    detection: [
      "Nature/inevitability metaphors applied to social arrangements: 'it's human nature', 'it's just how things work'",
      "Passive constructions that remove agency: 'inequality exists', 'these things happen'",
      "Historical timelessness claims: 'it's always been this way', 'this is how it's always worked'",
      "Absence of agent in descriptions of outcomes that have identifiable causes",
    ],
    userLabel: "Naturalisation - a social arrangement that was constructed and chosen is being presented as natural or inevitable, which conceals the interests it serves.",
    level: 3,
  },
  {
    id: "P3",
    name: "Manufactured Consensus",
    plainName: "False impression of universal agreement",
    definition: "The construction of an impression of widespread agreement where significant disagreement exists, exploiting the social proof heuristic - the cognitive tendency to infer correctness from apparent consensus. Silences legitimate dissent by making it appear marginal, eccentric, or dangerous.",
    theory: "Spiral of silence - perceived majority opinion suppresses minority expression (Noelle-Neumann, 1974); Social proof (Cialdini, 2001); Asch conformity experiments (1951); Astroturfing as manufactured consensus technique (Cho et al., 2011).",
    detection: [
      "Consensus-implying language without evidential basis: 'everyone agrees', 'no serious person disputes'",
      "Marginalisation of dissent: 'only fringe voices claim', 'no credible expert believes'",
      "False polling or survey invocations without citation",
      "Collective voice constructions: 'the people demand', 'the nation has spoken'",
    ],
    userLabel: "False consensus - this implies that everyone or most people agree, but the actual level of agreement may be much lower or more contested.",
    level: 3,
  },
  {
    id: "P4",
    name: "Epistemic Marginalisation",
    plainName: "Whose knowledge counts",
    definition: "The systematic devaluation or erasure of certain ways of knowing, certain sources of knowledge, or certain knowers - typically those associated with marginalised communities, non-Western traditions, lived experience, or non-credentialled expertise. Concentrates epistemic authority in already-powerful hands while delegitimising challenges from below.",
    theory: "Epistemic injustice - testimonial injustice and hermeneutical injustice (Fricker, 2007); Standpoint epistemology (Hartsock, 1983; Collins, 1990); Knowledge/power nexus (Foucault, 1980).",
    detection: [
      "Credentialism as gatekeeping: dismissing non-expert testimony without engaging content",
      "Experiential knowledge dismissal: 'that's just anecdote', 'feelings aren't evidence'",
      "Source origin bias markers: geographically, culturally, or class-coded dismissals",
      "Absence of voices from affected communities in discussions that primarily affect them",
    ],
    userLabel: "Whose knowledge counts - certain voices or ways of knowing are being excluded or dismissed. Consider who is absent from this account.",
    level: 3,
  },
  {
    id: "P5",
    name: "Moral Licensing",
    plainName: "Good behaviour used to justify harm",
    definition: "The invocation of established moral credentials - past good behaviour, stated values, identity as a good person - to create psychological permission for actions that would otherwise be evaluated as morally problematic. The established goodness functions as credit that can be spent on questionable behaviour.",
    theory: "Moral licensing effect (Monin & Miller, 2001); Moral disengagement - moral justification mechanism (Bandura, 1999); Motivated reasoning and self-concept maintenance (Tavris & Aronson, 2007).",
    detection: [
      "Credential invocation preceding problematic claim: 'as someone who has always supported [group]...'",
      "Historical virtue claims preceding contemporary problematic positions",
      "'I'm not X but...' constructions (not racist but..., not sexist but...)",
      "Charity/goodwill invocation before request for exception to moral principle",
    ],
    userLabel: "Moral licensing - past good behaviour or stated values are being used to justify a position that might otherwise be challenged. Good intentions don't automatically validate specific claims.",
    level: 3,
  },
  {
    id: "P6",
    name: "Grievance Weaponisation",
    plainName: "Real pain redirected toward a target",
    definition: "The exploitation of legitimate community grievances - real experiences of injustice, economic hardship, cultural anxiety, or political betrayal - to redirect emotional energy toward predetermined targets that serve the interests of the content producer rather than the community experiencing the grievance. The pain is real; the diagnosis and solution are manufactured.",
    theory: "Authoritarian populism - articulation of popular grievances to reactionary projects (Hall, 1979); Relative deprivation theory (Gurr, 1970); Information operations - grievance amplification as documented technique (NATO StratCom, 2021).",
    detection: [
      "Legitimate grievance acknowledgement followed by out-group blame attribution",
      "Emotional validation of real pain followed by manufactured causal explanation",
      "Amplification markers - intensity of grievance language disproportionate to evidential basis",
      "Transition from 'you have been wronged' to 'by [specific target]' without evidential bridge",
    ],
    userLabel: "Grievance weaponisation - a real pain or injustice is being acknowledged and then redirected toward a specific target. Your legitimate anger may be being used for someone else's purposes.",
    level: 3,
  },
];
